import React, { Component } from 'react'
import Home from '../../layouts/Home'
import { Grid } from '@material-ui/core/'
import CardContent from '@material-ui/core/CardContent';
import Typography from '@material-ui/core/Typography';
import { withStyles } from '@material-ui/core/styles';
import Card from '@material-ui/core/Card';

const styles = theme => ({
    root: {
        flexGrow: 1,
        marginTop: '5%',
    },
    card: {
        marginTop: '10%',
        marginBottom: '5%',
        maxWidth: '100%',
    },

});

class PrivacyPolicy extends Component {
    render() {
        const { classes } = this.props
        return (
            <Home>
                <Grid item className={classes.root}>
                    <Card className={classes.card}>
                        <CardContent>
                            <Typography variant="title" gutterBottom > Privacy Policy </Typography>
                            <Typography variant="overline" align="right" gutterBottom> Effective date: January 20, 2019 </Typography>
                            <Typography component="p" variant="body1" align="left">
                                CHI operates the “https://app-chi.firebaseapp.com/upin” website and
                                the CHI mobile application (referred to as the "Service").
                                This page informs you of our policies regarding the collection, use,
                                and disclosure of personal data when you use our Service and the choices
                                you have associated with that data. The Privacy Policy for CHI is based
                                on the TermsFeed's Privacy Policy Template.
                                We use your data to provide and improve the Service.
                                By using the Service, you agree to the collection and use of information
                                in accordance with this policy. Unless otherwise defined in this Privacy Policy,
                                the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.
                        </Typography>
                        </CardContent>

                        <CardContent>
                            <Typography variant="subtitle1" align="left" gutterBottom> Definitions </Typography>
                            <Typography variant="subtitle2" align="left" gutterBottom> 1. Service </Typography>
                            <Typography component="p" variant="body1" align="left">
                                Service means the https://app-chi.firebaseapp.com/upin website and
                                the CHI mobile application operated by CHI
                            </Typography>
                            <Typography variant="subtitle2" align="left" gutterBottom> 2. Personal Data </Typography>
                            <Typography component="p" variant="body1" align="left">
                                Personal Data means data about a living individual who can be identified
                                    from those data (or from those and other information either in our
                                    possession or likely to come into our possession).
                            </Typography>
                            <Typography variant="subtitle2" align="left" gutterBottom> 3. Usage Data </Typography>
                            <Typography component="p" variant="body1" align="left">
                                Usage Data is data collected automatically either generated by
                                    the use of the Service or from the Service infrastructure itself
                                    (for example, the duration of a page visit).
                            </Typography>
                            <Typography variant="subtitle2" align="left" gutterBottom> 4. Cookies </Typography>
                            <Typography component="p" variant="body1" align="left">
                                Cookies are small files stored on your device (computer or mobile device).
                            </Typography>
                        </CardContent>

                        <CardContent>
                            <Typography variant="subtitle1" align="left" gutterBottom> Information Collection and Use </Typography>
                            <Typography component="p" variant="body1" align="left">
                                We collect several different types of information for various purposes to provide and improve our Service to you.
                                Our Service does use third party services that may collect information used to identify you.
                                Please see the privacy policy of these third-party service providers which used by our Service.
                                </Typography>
                            <Typography component="p" variant="body1" align="left">
                                -	Facebook
                        </Typography>
                            <Typography component="p" variant="body1" align="left">
                                -	Firebase Analytics
                        </Typography>
                        </CardContent>

                        <CardContent>
                            <Typography variant="subtitle1" align="left" gutterBottom> Types of Data Collected </Typography>
                            <Typography variant="subtitle2" align="left" gutterBottom> 1. Personal Data </Typography>
                            <Typography component="p" variant="body1" align="left">
                                While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:
                            </Typography>
                            <Typography component="p" variant="body1" align="left">
                                •	Email address
                        </Typography>
                            <Typography component="p" variant="body1" align="left">
                                •	First name and last name
                        </Typography>
                            <Typography component="p" variant="body1" align="left">
                                •	Profile images
                        </Typography>
                            <Typography component="p" variant="body1" align="left" gutterBottom>
                                •	Cookies and Usage Data
                        </Typography>
                            <Typography variant="subtitle2" align="left" gutterBottom> 2. Usage Data </Typography>
                            <Typography component="p" variant="body1" align="left" gutterBottom>
                                We may also collect information that your browser sends whenever you visit our Service or when you access the Service by or through a mobile device ("Usage Data").
                                This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
                                When you access the Service by or through a mobile device, this Usage Data may include information such as the type of mobile device you use, your mobile device unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, unique device identifiers and other diagnostic data.
                        </Typography>
                            <Typography variant="subtitle2" align="left" gutterBottom> 3. Tracking Cookies Data </Typography>
                            <Typography component="p" variant="body1" align="left" gutterBottom>
                                We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.
                                Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyse our Service.
                                You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.
                        </Typography>
                            <Typography variant="subtitle2" align="left" gutterBottom> Examples of Cookies we use: </Typography>
                            <Typography component="p" variant="body1" align="left" gutterBottom>
                                •	Session Cookies: We use Session Cookies to operate our Service.
                        </Typography>
                            <Typography component="p" variant="body1" align="left" gutterBottom>
                                •	Preference Cookies: We use Preference Cookies to remember your preferences and various settings.
                        </Typography>
                            <Typography component="p" variant="body1" align="left" gutterBottom>
                                •	Security Cookies: We use Security Cookies for security purposes.
                        </Typography>
                        </CardContent>

                        <CardContent>
                            <Typography variant="subtitle1" align="left" gutterBottom> Use of Data </Typography>
                            <Typography component="p" variant="body1" align="left">
                                CHI uses the collected data for various purposes:
                            </Typography>
                            <Typography component="p" variant="body1" align="left">
                                •	To provide and maintain the Service
                            </Typography>
                            <Typography component="p" variant="body1" align="left">
                                •	To notify you about changes to our Service
                            </Typography>
                            <Typography component="p" variant="body1" align="left">
                                •	To allow you to participate in interactive features of our Service when you choose to do so
                            </Typography>
                            <Typography component="p" variant="body1" align="left" gutterBottom>
                                •	To provide customer care and support
                            </Typography>
                            <Typography component="p" variant="body1" align="left">
                                •	To provide analysis or valuable information so that we can improve the Service
                            </Typography>
                            <Typography component="p" variant="body1" align="left">
                                •	To monitor the usage of the Service
                            </Typography>
                            <Typography component="p" variant="body1" align="left" gutterBottom>
                                •	To detect, prevent and address technical issues
                            </Typography>
                        </CardContent>

                        <CardContent>
                            <Typography variant="subtitle1" align="left" gutterBottom> Transfer Of Data </Typography>
                            <Typography component="p" variant="body1" align="left">
                                Your information, including Personal Data, may be transferred to - and maintained on - computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from your jurisdiction.
                                If you are located outside Thailand and choose to provide information to us, please note that we transfer the data, including Personal Data, to Thailand and process it there.
                                Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.
                                CHI will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless
                                there are adequate controls in place including the security of your data and other personal information.
                            </Typography>
                        </CardContent>

                        <CardContent>
                            <Typography variant="subtitle1" align="left" gutterBottom> Disclosure Of Data </Typography>
                            <Typography variant="subtitle2" align="left" gutterBottom> Legal Requirements </Typography>
                            <Typography component="p" variant="body1" align="left">
                                CHI may disclose your Personal Data in the good faith belief that such action is necessary to:
                                </Typography>
                            <Typography component="p" variant="body1" align="left" gutterBottom>
                                •	To comply with a legal obligation
                        </Typography>
                            <Typography component="p" variant="body1" align="left">
                                •	To protect and defend the rights or property of CHi
                        </Typography>
                            <Typography component="p" variant="body1" align="left">
                                •	To prevent or investigate possible wrongdoing in connection with the Service
                        </Typography>
                            <Typography component="p" variant="body1" align="left" gutterBottom>
                                •	To protect the personal safety of users of the Service or the public
                        </Typography>
                            <Typography component="p" variant="body1" align="left" gutterBottom>
                                •	To protect against legal liability
                        </Typography>
                            <Typography component="p" variant="body1" align="left" gutterBottom>
                                As an European citizen, under GDPR, you have certain individual rights.
                                You can learn more about these guides in the GDPR Guide.
                            </Typography>
                        </CardContent>

                        <CardContent>
                            <Typography variant="subtitle1" align="left" gutterBottom> Security of Data </Typography>
                            <Typography component="p" variant="body1" align="left">
                                The security of your data is important to us but remember that no method of transmission over
                                the Internet or method of electronic storage is 100% secure.
                                While we strive to use commercially acceptable means to protect your Personal Data,
                                we cannot guarantee its absolute security.
                            </Typography>
                        </CardContent>

                        <CardContent>
                            <Typography variant="subtitle1" align="left" gutterBottom> Service Providers </Typography>
                            <Typography component="p" variant="body1" align="left">
                                We may employ third party companies and individuals to facilitate our Service ("Service Providers"),
                                to provide the Service on our behalf, to perform Service-related services or to assist us in analyzing
                                how our Service is used. These third parties have access to your Personal Data only to perform these
                                tasks on our
                                behalf and are obligated not to disclose or use it for any other purpose.
                            </Typography>
                        </CardContent>

                        <CardContent>
                            <Typography variant="subtitle1" align="left" gutterBottom> Links to Other Sites </Typography>
                            <Typography component="p" variant="body1" align="left">
                                Our Service may contain links to other sites that are not operated by us. If you click a third party link,
                                you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.
                                We have no control over and assume no responsibility for the content, privacy policies or practices of
                                any third-party sites or services.
                            </Typography>
                        </CardContent>

                        <CardContent>
                            <Typography variant="subtitle1" align="left" gutterBottom> Changes to This Privacy Policy </Typography>
                            <Typography component="p" variant="body1" align="left">
                                We may update our Privacy Policy from time to time. We will notify you of any changes by posting
                                the new Privacy Policy on this page.
                                We will let you know via email and/or a prominent notice on our Service, prior to the change becoming
                                effective and update the "effective date" at the top of this Privacy Policy.
                                You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy
                                are effective when they are posted on this page.
                            </Typography>
                        </CardContent>

                        <CardContent>
                            <Typography variant="subtitle1" align="right">  "CHI Developer's Team." </Typography>
                        </CardContent>
                    </Card>
                </Grid>
            </Home>
        )
    }
}
export default withStyles(styles, { withTheme: true })(PrivacyPolicy)